# =============================================================================
# Silver Tier AI Employee — Daily Scheduler (Windows / PowerShell)
# =============================================================================
# Purpose : Run Claude at 8 AM every day, generate a daily briefing from
#           /Done files, and write the result to /Logs/daily_briefing_[date].md
#
# SETUP — WINDOWS TASK SCHEDULER
# --------------------------------
# Option A — PowerShell one-liner (run once as Administrator):
#
#   $action  = New-ScheduledTaskAction -Execute "powershell.exe" `
#                -Argument "-NonInteractive -ExecutionPolicy Bypass -File `"C:\path\to\schedulers\daily_scheduler.ps1`""
#   $trigger = New-ScheduledTaskTrigger -Daily -At 08:00
#   $settings = New-ScheduledTaskSettingsSet -StartWhenAvailable
#   Register-ScheduledTask -TaskName "SilverTier-DailyBriefing" `
#                          -Action $action -Trigger $trigger `
#                          -Settings $settings -RunLevel Highest -Force
#
#   Replace C:\path\to\ with the actual absolute path to this project.
#
# Option B — Task Scheduler GUI:
#   1. Open Task Scheduler  (Win+R → taskschd.msc)
#   2. "Create Basic Task" → Name: SilverTier-DailyBriefing
#   3. Trigger → Daily, Start: 8:00 AM
#   4. Action → Start a Program
#        Program : powershell.exe
#        Arguments: -NonInteractive -ExecutionPolicy Bypass -File "C:\path\to\schedulers\daily_scheduler.ps1"
#   5. Finish → check "Open properties dialog" → General tab → "Run whether user is logged on or not"
#   6. OK → enter your Windows password to save
#
# VERIFY TASK EXISTS
# ------------------
#   Get-ScheduledTask -TaskName "SilverTier-DailyBriefing"
#
# REMOVE TASK
# -----------
#   Unregister-ScheduledTask -TaskName "SilverTier-DailyBriefing" -Confirm:$false
#
# MANUAL TEST
# -----------
#   powershell -ExecutionPolicy Bypass -File "C:\path\to\schedulers\daily_scheduler.ps1"
#   Then check: C:\path\to\Logs\daily_briefing_YYYY-MM-DD.md
# =============================================================================

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

# ---------------------------------------------------------------------------
# Configuration — VAULT_ROOT is derived automatically from script location
# ---------------------------------------------------------------------------
$VaultRoot  = Split-Path -Parent $PSScriptRoot     # project root (one level up)
$DoneDir    = Join-Path $VaultRoot "Done"
$LogsDir    = Join-Path $VaultRoot "Logs"
$Date       = Get-Date -Format "yyyy-MM-dd"
$OutputFile = Join-Path $LogsDir "daily_briefing_$Date.md"
$LogFile    = Join-Path $LogsDir "scheduler.log"

# Ensure Logs directory exists
if (-not (Test-Path $LogsDir)) { New-Item -ItemType Directory -Path $LogsDir | Out-Null }

function Write-Log {
    param([string]$Message)
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $line = "[$ts] $Message"
    Write-Host $line
    Add-Content -Path $LogFile -Value $line
}

Write-Log "Starting daily briefing generation..."

# ---------------------------------------------------------------------------
# Collect Done files
# ---------------------------------------------------------------------------
$DoneFiles = @()
if (Test-Path $DoneDir) {
    $DoneFiles = Get-ChildItem -Path $DoneDir -Recurse -Filter "*.md" -Depth 2 |
                 Sort-Object Name
}

$DoneContent = ""
if ($DoneFiles.Count -gt 0) {
    foreach ($file in $DoneFiles) {
        $fname   = $file.Name
        $content = Get-Content -Path $file.FullName -TotalCount 60 | Out-String
        $DoneContent += "`n`n---`n### File: $fname`n$content"
    }
} else {
    $DoneContent = "No completed files found in /Done today."
}

# ---------------------------------------------------------------------------
# Prompt for Claude
# ---------------------------------------------------------------------------
$Prompt = @"
You are a Silver Tier AI Employee assistant. Today is $Date.

Review the following completed task files from the /Done folder and produce a concise daily briefing in Markdown.

Format the output as:
# Daily Briefing — $Date

## Summary
(2-3 sentence overview of what was accomplished today)

## Completed Tasks
(bullet list of tasks, one per Done file found)

## Key Highlights
(any notable outcomes, blockers resolved, or patterns worth flagging)

## Recommended Next Actions
(3-5 actionable suggestions based on completed work)

---
*Auto-generated by Silver Tier Daily Scheduler*

DONE FILES CONTENT:
$DoneContent
"@

# ---------------------------------------------------------------------------
# Check for Claude CLI
# ---------------------------------------------------------------------------
$ClaudePath = (Get-Command claude -ErrorAction SilentlyContinue)?.Source
if (-not $ClaudePath) {
    Write-Log "ERROR: 'claude' CLI not found. Install it with: npm install -g @anthropic-ai/claude-code"
    exit 1
}

Write-Log "Calling Claude CLI..."

# ---------------------------------------------------------------------------
# Run Claude and capture output
# ---------------------------------------------------------------------------
try {
    $Output = & claude --print $Prompt 2>&1
    $Output | Set-Content -Path $OutputFile -Encoding UTF8
    Write-Log "SUCCESS — briefing written to: $OutputFile"
}
catch {
    Write-Log "ERROR — $($_.Exception.Message)"
    exit 1
}
