#!/usr/bin/env bash
# =============================================================================
# Silver Tier AI Employee — Daily Scheduler (Linux / macOS)
# =============================================================================
# Purpose : Run Claude at 8 AM every day, generate a daily briefing from
#           /Done files, and write the result to /Logs/daily_briefing_[date].md
#
# SETUP — CRONTAB
# ---------------
# 1. Make this script executable:
#      chmod +x /path/to/schedulers/daily_scheduler.sh
#
# 2. Open crontab editor:
#      crontab -e
#
# 3. Add the following line (runs every day at 8:00 AM):
#      0 8 * * * /path/to/schedulers/daily_scheduler.sh >> /path/to/Logs/cron.log 2>&1
#
#    Replace /path/to/ with the absolute path to this project, e.g.:
#      0 8 * * * /Users/yourname/silver-tier/schedulers/daily_scheduler.sh >> /Users/yourname/silver-tier/Logs/cron.log 2>&1
#
# 4. Save and exit (in vim: :wq  |  in nano: Ctrl+O, Ctrl+X)
#
# 5. Verify cron entry was saved:
#      crontab -l
#
# MANUAL TEST
# -----------
#   bash /path/to/schedulers/daily_scheduler.sh
#   Then check: /path/to/Logs/daily_briefing_YYYY-MM-DD.md
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration — adjust VAULT_ROOT to match your actual project path
# ---------------------------------------------------------------------------
VAULT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
DONE_DIR="$VAULT_ROOT/Done"
LOGS_DIR="$VAULT_ROOT/Logs"
DATE=$(date +"%Y-%m-%d")
OUTPUT_FILE="$LOGS_DIR/daily_briefing_${DATE}.md"

# Ensure Logs directory exists
mkdir -p "$LOGS_DIR"

# ---------------------------------------------------------------------------
# Collect files completed today (or all files if none match today)
# ---------------------------------------------------------------------------
echo "[$(date '+%Y-%m-%d %H:%M:%S')] Starting daily briefing generation..." >&2

DONE_FILES=$(find "$DONE_DIR" -maxdepth 2 -name "*.md" -newer "$DONE_DIR" 2>/dev/null | sort)

if [ -z "$DONE_FILES" ]; then
  # Fall back to all .md files in /Done
  DONE_FILES=$(find "$DONE_DIR" -maxdepth 2 -name "*.md" 2>/dev/null | sort)
fi

DONE_COUNT=$(echo "$DONE_FILES" | grep -c '.' 2>/dev/null || echo 0)

# Build a concatenated snapshot of Done files (truncated to avoid token limits)
DONE_CONTENT=""
if [ "$DONE_COUNT" -gt 0 ]; then
  while IFS= read -r f; do
    [ -f "$f" ] || continue
    FNAME=$(basename "$f")
    FCONTENT=$(head -n 60 "$f")   # first 60 lines per file
    DONE_CONTENT="${DONE_CONTENT}\n\n---\n### File: ${FNAME}\n${FCONTENT}"
  done <<< "$DONE_FILES"
fi

# ---------------------------------------------------------------------------
# Prompt for Claude
# ---------------------------------------------------------------------------
PROMPT="You are a Silver Tier AI Employee assistant. Today is ${DATE}.

Review the following completed task files from the /Done folder and produce a concise daily briefing in Markdown.

Format the output as:
# Daily Briefing — ${DATE}

## Summary
(2-3 sentence overview of what was accomplished today)

## Completed Tasks
(bullet list of tasks, one per Done file found)

## Key Highlights
(any notable outcomes, blockers resolved, or patterns worth flagging)

## Recommended Next Actions
(3-5 actionable suggestions based on completed work)

---
*Auto-generated by Silver Tier Daily Scheduler*

DONE FILES CONTENT:
${DONE_CONTENT:-No completed files found in /Done today.}"

# ---------------------------------------------------------------------------
# Run Claude and capture output
# ---------------------------------------------------------------------------
if ! command -v claude &>/dev/null; then
  echo "[ERROR] 'claude' CLI not found. Install it with: npm install -g @anthropic-ai/claude-code" >&2
  exit 1
fi

echo "[$(date '+%Y-%m-%d %H:%M:%S')] Calling Claude CLI..." >&2

claude --print "$PROMPT" > "$OUTPUT_FILE" 2>&1

EXIT_CODE=$?

if [ $EXIT_CODE -eq 0 ]; then
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] SUCCESS — briefing written to: $OUTPUT_FILE" >&2
else
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR — Claude exited with code $EXIT_CODE. Check $OUTPUT_FILE for details." >&2
  exit $EXIT_CODE
fi

# ---------------------------------------------------------------------------
# Weekly Audit Briefer — runs every Sunday (day-of-week == 7 in ISO format)
# ---------------------------------------------------------------------------
# date +%u returns: 1=Monday … 7=Sunday
if [ "$(date +%u)" = "7" ]; then
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] Sunday detected — running Weekly Audit Briefer (Skill 8)..." >&2

  WEEKLY_SCRIPT="$VAULT_ROOT/Skills/weekly_audit_briefer.py"

  if ! command -v python3 &>/dev/null && ! command -v python &>/dev/null; then
    echo "[ERROR] Python not found. Cannot run Weekly Audit Briefer." >&2
  elif [ ! -f "$WEEKLY_SCRIPT" ]; then
    echo "[ERROR] weekly_audit_briefer.py not found at: $WEEKLY_SCRIPT" >&2
  else
    PYTHON_CMD="python3"
    command -v python3 &>/dev/null || PYTHON_CMD="python"

    WEEKLY_OUTPUT=$("$PYTHON_CMD" "$WEEKLY_SCRIPT" 2>&1)
    WEEKLY_EXIT=$?

    if [ $WEEKLY_EXIT -eq 0 ]; then
      # Extract briefing path from output (last line matching "Briefing Path")
      BRIEFING_PATH=$(echo "$WEEKLY_OUTPUT" | grep -oP '(?<=Briefing Path : ).*' | tail -1)
      echo "[$(date '+%Y-%m-%d %H:%M:%S')] Weekly audit complete — ${BRIEFING_PATH:-see output}" >&2
    else
      echo "[$(date '+%Y-%m-%d %H:%M:%S')] ERROR — Weekly Audit Briefer exited with code $WEEKLY_EXIT" >&2
      echo "$WEEKLY_OUTPUT" >&2
    fi
  fi
else
  echo "[$(date '+%Y-%m-%d %H:%M:%S')] Not Sunday (day=$(date +%u)) — skipping Weekly Audit Briefer." >&2
fi
